---
##  Interacts with webservices to get Oauth token
- name: Include secrets
  include_vars: ../defaults/secrets.yml
  no_log: true

- name: Verify Temporary Install Directory Exists
  tempfile:
    path: "{{ falcon_install_tmp_dir }}"
    state: directory
    suffix: falcon
  when:
    - falcon_install_tmp_dir is defined
  register: falcon_install_temp_directory
  changed_when: false

- name: Authenticate to CrowdStrike API
  uri:
    url: "https://{{ falcon_cloud }}/oauth2/token"
    method: POST
    body_format: json
    body:
      "client_id={{ falcon_client_id }}&client_secret={{ falcon_client_secret }}"
    return_content: true
    follow_redirects: all
    status_code: 201
    headers:
      content-type: application/x-www-form-urlencoded
  register: falcon_api_oauth2_token
  no_log: true

- name: Download Falcon Sensor Installation Package
  get_url:
    url: "https://{{ falcon_cloud }}/sensors/entities/download-installer/v1?id={{ falcon_instaler_id }}"
    dest: "{{ falcon_install_temp_directory.path }}"
    headers:
      authorization: "Bearer {{ falcon_api_oauth2_token.json.access_token }}"
  changed_when: false
  register: falcon_sensor_download
  no_log: true

- name: Set full file download path
  set_fact:
    falcon_sensor_pkg: "{{ falcon_sensor_download.dest }}"
