---

## Install the package using a generic packer manager
- name: Install Falcon Sensor Package (Linux)
  become: true
  package:
    deb: "{{ falcon_sensor_pkg }}"
    state: present

- name: Configure Falcon Sensor Options
  shell:
    cmd: "/opt/CrowdStrike/falconctl -s --cid={{ falcon_cid }} --provisioning-token={{ falcon_provisioning_token }}"
  become: yes
  ignore_errors: yes
  notify: Restart Falcon Sensor

# handlers file for falcon_configure
- name: Restart Falcon Sensor
  service:
    name: falcon-sensor
    state: "{{ falcon_service_state | default('restarted') }}"
    enabled: yes
  become: yes

- name: Gather tmp install directory objects
  find:
    paths: "{{ falcon_install_tmp_dir }}"
    patterns: "ansible.*falcon"
    file_type: directory
  register: falcon_tmp_dir_objects
  when: falcon_install_tmp_dir|length > 0
  changed_when: no

- name: Remove tmp install directories
  file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ falcon_tmp_dir_objects.files }}"
  when:
    - falcon_install_tmp_dir|length > 0
    - falcon_tmp_dir_objects is defined and falcon_tmp_dir_objects.files|length > 0
  changed_when: no
