---
## Install the package using a generic packer manager
- name: Install Falcon Sensor Package (Linux)
  ansible.builtin.package:
    name: "{{ falcon_sensor_pkg }}"
    state: present
  debugger: always

- name: Configure Falcon Sensor Options
  ansible.builtin.shell:
    cmd: "/opt/CrowdStrike/falconctl -s --cid={{ falcon_cid }} --provisioning-token={{ falcon_provisioning_token }}"
  become: yes
  become_method: sudo
  notify: Restart Falcon Sensor
  debugger: always
    

# handlers file for falcon_configure
- name: Restart Falcon Sensor
  ansible.builtin.service:
    name: falcon-sensor
    state: "{{ falcon_service_state | default('restarted') }}"
    enabled: yes
  become: yes
  debugger: always


- name: Gather tmp install directory objects
  ansible.builtin.find:
    paths: "{{ falcon_install_tmp_dir }}"
    patterns: "ansible.*falcon"
    file_type: directory
  register: falcon_tmp_dir_objects
  when: falcon_install_tmp_dir|length > 0
  changed_when: no

- name: Remove tmp install directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ falcon_tmp_dir_objects.files }}"
  when:
    - falcon_install_tmp_dir|length > 0
    - falcon_tmp_dir_objects is defined and falcon_tmp_dir_objects.files|length > 0
  changed_when: no

    